disabled_rules: # rule identifiers turned on by default to exclude from running
    #  - line_length
    - force_cast
    #  - force_try
    - identifier_name
    - cyclomatic_complexity
#  - function_body_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
cyclomatic_complexity:
    ignores_case_statements: true
    warning: 47
line_length:
    warning: 185
    ignores_function_declarations: true
    ignores_comments: true
    ignores_interpolated_strings: true
    ignores_urls: true
